codetatvaacademy/GU-Technical-Training-2026

YuvrajSingh/CheckEvenOdd.cpp, YuvrajSingh/Circle.cpp, YuvrajSingh/Convert2Paise.cpp, YuvrajSingh/CountString.cpp, YuvrajSingh/IncomeTax.cpp, YuvrajSingh/Largest.cpp, YuvrajSingh/LowerUper.cpp, YuvrajSingh/MovieMagic.cpp, YuvrajSingh/ParkingLot.cpp, YuvrajSingh/SquareAndCubeOfNumber.cpp, YuvrajSingh/SumOf2Number.cpp
=> Yuvraj singh

Ankit-Raj-01/text.md
=> First Commit

DheerajKumar/Technical-Training-2026/PrefixSum/day2Q2270.cpp, DheerajKumar/Technical-Training-2026/PrefixSum/day2Q238.cpp, DheerajKumar/Technical-Training-2026/PrefixSum/day2Q724.cpp
daily streak problem (`prefixsum 2270`). & question no `238` & `724`
=> Addition of prefix problems

Chelsi_Singh/Readme.txt, Chelsi_Singh/Sum2D.java
=> Pull request

YashVats/redme.md
=> addition of readme file

LovelyKumari/PrefixAndSuffixSum/NumMatrix.java, LovelyKumari/PrefixAndSuffixSum/Problem01.java, LovelyKumari/PrefixAndSuffixSum/Problem02.java, LovelyKumari/readme.md
=> test file Submission

AAMIR_KHAN/PREFIXSUMASSESMENT/Find the Middle Index in Array
class Solution {
public int findMiddleIndex(int[] nums) {
int[] leftSum= new int[nums.length];
int[] rightSum= new int[nums.length];
leftSum[0]=nums[0];
for(int i=1;i<nums.length;i++){
leftSum[i]=leftSum[i-1]+nums[i];
}
rightSum[nums.length-1]=nums[nums.length-1];
for(int i=nums.length-2;  i>=0;i--){
rightSum[i]=rightSum[i+1]+nums[i];
}
for(int i=0; i<nums.length;i++){
if(leftSum[i]== rightSum[i]){
return i;
}
}
return -1;
}
}
=> Find the Middle Index in Array

Aditya Pratap SIngh/PrefixSumAssessment/Problem1.py, Aditya Pratap SIngh/PrefixSumAssessment/Problem2.py, Aditya Pratap SIngh/PrefixSumAssessment/Problem3.py, Aditya Pratap SIngh/PrefixSumAssessment/README.md
=> AdityaPratap_Pullrequest

DheerajKumar/Technical-Training-2026/PrefixSum/Test/testPrefixSumQuestion3.cpp, DheerajKumar/readme.md
=> Practice of Test problems after Exams

Ashish kumar/problem1.cpp, Ashish kumar/problem2.cpp, Ashish kumar/readme.md
=> 1st and 2nd question

SurajKumarSingh/TechnicalTranning2026/testProblem1.java, SurajKumarSingh/problem01.java, SurajKumarSingh/problem02.java, SurajKumarSingh/problem03.java, SurajKumarSingh/problem04.java
=> addition of problem1 basic code learning.

DheerajKumar/Technical-Training-2026/PrefixSum/dailyStreakProblem2381.cpp, DheerajKumar/Technical-Training-2026/TopInterviewQuestion/eassyCollection/array/problem122.cpp, DheerajKumar/Technical-Training-2026/TopInterviewQuestion/eassyCollection/array/problem26.cpp, DheerajKumar/readme.md
=> Addition of Top Interview Question Easy Collection

PoojaKumari/2DMatrix/RichestCustomerWealth.java, PoojaKumari/2DMatrix/SpiralMatrix.java
=>  Adding Richest Customer Wealth and Spiral Matrix Problem solution with user input

DheerajKumar/Technical-Training-2026/BinarySearch/problem1011.cpp, DheerajKumar/Technical-Training-2026/BinarySearch/problem1482.cpp, DheerajKumar/Technical-Training-2026/BinarySearch/problem1552.cpp, DheerajKumar/Technical-Training-2026/BinarySearch/problem2141.cpp, DheerajKumar/Technical-Training-2026/BinarySearch/problem826.cpp, DheerajKumar/Technical-Training-2026/BinarySearch/question1760.cpp, DheerajKumar/Technical-Training-2026/PrefixSum/dailyPracticeProblem2185.cpp
prefix Daily Question leetcode 2185 Addition
=> Addition of Problems

SurajKumarSingh/BinarySearch/BallInBag.java, SurajKumarSingh/BinarySearch/CapicityToShip.java, SurajKumarSingh/BinarySearch/MaximumNComputer.java, SurajKumarSingh/BinarySearch/ThresholdValue.java
=> additon of problems

DheerajKumar/Technical-Training-2026/BinarySearch/problem33.cpp, DheerajKumar/Technical-Training-2026/BinarySearch/problem367.cpp
Added **`33`** & **`367`** problem No.
=> Addition of Problem

SurajKumarSingh/BinarySearch/BallInBag.java, SurajKumarSingh/BinarySearch/ThresholdValue.java, SurajKumarSingh/TwoDArray/CountNegativeNumber.java, SurajKumarSingh/TwoDArray/DiagonalSum.java, SurajKumarSingh/TwoDArray/DigonalSum.java, SurajKumarSingh/TwoDArray/OneDTwoD.java, SurajKumarSingh/TwoDArray/RichestWelth.java, SurajKumarSingh/TwoDArray/RotateImage.java, SurajKumarSingh/TwoDArray/SetMatrixZeros.java, SurajKumarSingh/TwoDArray/SpiralMatrix.java, SurajKumarSingh/TwoDArray/SpiralMatrixII.java, SurajKumarSingh/TwoDArray/TransposeMatrix.java, SurajKumarSingh/Week2test/testProblem01.java, SurajKumarSingh/Week2test/testProblem02.java, SurajKumarSingh/prefixsum/HighestAltitude.java, SurajKumarSingh/prefixsum/MatrixBlockSum.java, SurajKumarSingh/prefixsum/MaxumumSplit.java, SurajKumarSingh/prefixsum/MinimumStepSum.java, SurajKumarSingh/prefixsum/PivotIndex.java, SurajKumarSingh/prefixsum/ProductSelf.java, SurajKumarSingh/prefixsum/RangeSum.java, SurajKumarSingh/prefixsum/ShiftingLetters.java, SurajKumarSingh/prefixsum/SumOfAbsolute.java, SurajKumarSingh/prefixsum/SumOfArray.java
Addition of assignment problems
=> addition of problems.

ShivanshuPandey/CountOccurrencesBinarySearch.java
Added CountOccurrencesBinarySearch.java
=> CountOccurrencesBinarySearch.java

ShivanshuPandey/KokoEatingBananas.java
=> KokoEatingBananas.java

ShivanshuPandey/MinimumTime.java
=> MinimumTime.java

ShivanshuPandey/MinimumWindowSubstring.java
add MinimumWindowSubstring.java
=> MinimumWindowSubstring.java

DheerajKumar/Technical-Training-2026/2pointer/problem.cpp, DheerajKumar/Technical-Training-2026/2pointer/problem1790.cpp, DheerajKumar/Technical-Training-2026/BinarySearch/problem633.cpp, DheerajKumar/Technical-Training-2026/HashMap-unordered_Map/problem2349.cpp, DheerajKumar/Technical-Training-2026/HashMap-unordered_Map/problem2364.cpp, DheerajKumar/Technical-Training-2026/all-Test/Test-31-1-25-slidingWindow/problem4.cpp, DheerajKumar/Technical-Training-2026/slidingWindow/problem1004.cpp, DheerajKumar/Technical-Training-2026/slidingWindow/problem1800.cpp, DheerajKumar/Technical-Training-2026/slidingWindow/problem713.cpp
test question code correction 
problem no - `4 semiRepetitiveString`
=> test question code correction

Gopal/project2/index.html, Gopal/project2/script.js, Gopal/project2/styles.css
=> Added my Project Stage 1

SadafFatima/README.md
Added my personal folder "SadafFatima" with a README file.
=> Added folder for Sadaf Fatima
